### PR TITLE
refactor: upgrade to debezium 3.2.4 and cherry-pick patch

### PR DESCRIPTION
**Pull request by zwang28**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

Bump debezium to v3.2.4, which requires Java 17.

Since we're applying copy-and-modify pattern to patch debezium, existing patches need be re-applied after upgrading debezium:
1. #18760 is cherry-picked to v3.2.4 files. A few conflicts have been resolved. refer to [this](https://github.com/zwang28/debezium/tree/v3.2.4.rw).
    - The new interface `HistorizedDatabaseSchema::getSchemaHistory` is implemented via a no-op new class `PostgresSchemaHistory`.
2. #23286 this patch is no longer needed since v3.2.4 debezium already support MySql 8.4.

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  I have checked the [Release Timeline](https://github.com/risingwavelabs/rw-commits-history/blob/main/release_timeline.md) and [Currently Supported Versions](https://docs.risingwave.com/changelog/release-support-policy#support-end-dates-for-recent-releases) to determine which release branches I need to cherry-pick this PR into. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

**Comment by zwang28** [comment]
> e2e_test/source_legacy/cdc/mongodb/mongodb_basic.slt

The mongodb cdc test failed.

**Comment by hzxa21** [comment]
```
query I
select count(*) from normalized_users;
----
55

# historical data
query I
select count(*) from users where commit_ts = '1970-01-01 00:00:00+00:00';
----
55
```

The first query passes but the second query returns 0. I think it is related to the timestamp changes in the meta column:
```
CREATE TABLE users (_id JSONB PRIMARY KEY, payload JSONB)
INCLUDE TIMESTAMP as commit_ts
```

**Comment by hzxa21** [comment]
Related to https://github.com/debezium/debezium/pull/6170

The fix is merged in version >= dbz 3.1

File: .github/workflows/connector-node-integration.yml [hunk 1]
```diff
@@ -13,7 +13,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        java: [ '11', '17' ]
+        java: [ '17' ]
```
Comment (xiangjinwu) [inline .github/workflows/connector-node-integration.yml]: Shall we enable tests against java 21 as well?

**Comment by zwang28** [comment]
> LGTM. Thanks for the efforts!
> 
> I saw that the `patched` comment are removed for the java code diff against dbz. Have we decided to use this [repo](https://github.com/zwang28/debezium/tree/v3.2.4.rw) to track the diff instead of noting that the diff in the codes?

Yes, we'll have a repo hosted in risingwave account for tracking purpose, not this personal one.

**Review by wcy-fdu — APPROVED** [review]
Thanks for the efforts!

File: .github/workflows/connector-node-integration.yml (hunk 1 above)
Comment (zwang28) [reply .github/workflows/connector-node-integration.yml]: Added java 21.

**Comment by xiangjinwu** [comment]
Are we still waiting for anything before merge?

**Comment by zwang28** [comment]
> Are we still waiting for anything before merge?

~~We'll merge this PR after the release-2.7 code-freeze.~~

UPDATE: we'll include this PR in release-2.7.

**Comment by xiangjinwu** [comment]
```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /risingwave/java/connector-node/risingwave-source-cdc/src/main/java/com/risingwave/connector/cdc/debezium/internal/NoDataRecoverySnapshotter.java:[41,70] cannot find symbol
  symbol:   method historyExists()
  location: interface io.debezium.schema.HistorizedDatabaseSchema
[INFO] 1 error
```
merge failure is due to conflict with #22255
