### ISSUE TITLE
failed to run connector integration test: `java.lang.NoSuchMethodError: 'io.grpc.MethodDescriptor$Marshaller`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#24627]
### Buildkite URL

https://buildkite.com/risingwavelabs/main-cron/builds/8590#019c01e7-6e75-418b-908e-c520daa1a3c7/L583

### Description and Insights

```
_bk;t=1769560093674Exception in thread "main" java.lang.NoSuchMethodError: 'io.grpc.MethodDescriptor$Marshaller io.grpc.protobuf.ProtoUtils.marshaller(com.google.protobuf.Message)'

_bk;t=1769560093674	at com.risingwave.proto.ConnectorServiceGrpc.getSinkWriterStreamMethod(ConnectorServiceGrpc.java:34)

_bk;t=1769560093674	at com.risingwave.proto.ConnectorServiceGrpc.getServiceDescriptor(ConnectorServiceGrpc.java:609)

_bk;t=1769560093674	at com.risingwave.proto.ConnectorServiceGrpc.bindService(ConnectorServiceGrpc.java:525)

_bk;t=1769560093674	at com.risingwave.proto.ConnectorServiceGrpc$ConnectorServiceImplBase.bindService(ConnectorServiceGrpc.java:276)

_bk;t=1769560093674	at io.grpc.internal.ServerImplBuilder.addService(ServerImplBuilder.java:145)

_bk;t=1769560093674	at io.grpc.internal.ServerImplBuilder.addService(ServerImplBuilder.java:57)

_bk;t=1769560093674	at io.grpc.ForwardingServerBuilder.addService(ForwardingServerBuilder.java:77)

_bk;t=1769560093674	at com.risingwave.connector.ConnectorService.main(ConnectorService.java:52)
```

Seems to be related to dependencies introduced in https://github.com/risingwavelabs/risingwave/pull/24457.
