### PR TITLE
fix: fix build on macos

### PR DESCRIPTION
**Pull request by wangrunji0408**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://gist.github.com/TennyZhuang/f00be7f16996ea48effb049aa7be4d66#file-rw_cla).

## What's changed and what's your intention?

Fix the compile error on macos introduced by #8253.

```
error[E0432]: unresolved import `tikv_jemalloc_ctl`
   --> src/compute/src/memory_management/policy.rs:220:9
    |
220 |     use tikv_jemalloc_ctl::{epoch as jemalloc_epoch, stats as jemalloc_stats};
    |         ^^^^^^^^^^^^^^^^^ use of undeclared crate or module `tikv_jemalloc_ctl`
```

## Checklist For Contributors

- [x] I have written necessary rustdoc comments
- [x] I have added necessary unit tests and integration tests
- [x] I have added fuzzing tests or opened an issue to track them. (Optional, recommended for new SQL features #7934).
- [x] I have demonstrated that backward compatibility is not broken by breaking changes and created issues to track deprecated features to be removed in the future. (Please refer to the issue)
- [x] All checks passed in `./risedev check` (or alias, `./risedev c`)

## Checklist For Reviewers

- [ ] I have requested macro/micro-benchmarks as this PR can affect performance substantially, and the results are shown.

## Documentation

- [x] My PR **DOES NOT** contain user-facing changes.

### CODE REVIEW

**Review by liurenjie1024 — APPROVED** [review]

**Comment by xx01cyx** [comment]
IIRC we do not support jemalloc allocator on operating systems other than linux. I'm thinking of the correctness of this fix. (Maybe it should be fixed in the code rather than Cargo.toml)

**Comment by BugenZhao** [comment]
Should we also enable jemalloc for macOS to make the value meaningful?

**Review by xx01cyx — APPROVED** [review]
Memory control is not performed on OS other than Linux yet, so I think we can merge this PR now to pass the compilation. Anyway, we have to provide the same memory control policies for all OS eventually.

**Comment by wangrunji0408** [comment]
Is this way acceptable?

**Comment by xx01cyx** [comment]
> Is this way acceptable? @xx01cyx

LGTM

**Review by BugenZhao — APPROVED** [review]
