### PR TITLE
fix(ci): avoid shaded gRPC classpath conflict in connector test

### LINKED ISSUE #24627: failed to run connector integration test: `java.lang.NoSuchMethodError: 'io.grpc.MethodDescriptor$Marshaller`
### Buildkite URL

https://buildkite.com/risingwavelabs/main-cron/builds/8590#019c01e7-6e75-418b-908e-c520daa1a3c7/L583

### Description and Insights

```
_bk;t=1769560093674Exception in thread "main" java.lang.NoSuchMethodError: 'io.grpc.MethodDescriptor$Marshaller io.grpc.protobuf.ProtoUtils.marshaller(com.google.protobuf.Message)'

_bk;t=1769560093674	at com.risingwave.proto.ConnectorServiceGrpc.getSinkWriterStreamMethod(ConnectorServiceGrpc.java:34)

_bk;t=1769560093674	at com.risingwave.proto.ConnectorServiceGrpc.getServiceDescriptor(ConnectorServiceGrpc.java:609)

_bk;t=1769560093674	at com.risingwave.proto.ConnectorServiceGrpc.bindService(ConnectorServiceGrpc.java:525)

_bk;t=1769560093674	at com.risingwave.proto.ConnectorServiceGrpc$ConnectorServiceImplBase.bindService(ConnectorServiceGrpc.java:276)

_bk;t=1769560093674	at io.grpc.internal.ServerImplBuilder.addService(ServerImplBuilder.java:145)

_bk;t=1769560093674	at io.grpc.internal.ServerImplBuilder.addService(ServerImplBuilder.java:57)

_bk;t=1769560093674	at io.grpc.ForwardingServerBuilder.addService(ForwardingServerBuilder.java:77)

_bk;t=1769560093674	at com.risingwave.connector.ConnectorService.main(ConnectorService.java:52)
```

Seems to be related to dependencies introduced in https://github.com/risingwavelabs/risingwave/pull/24457.

### PR DESCRIPTION
**Pull request by BugenZhao**
I hereby agree to the terms of the [RisingWave Labs, Inc. Contributor License Agreement](https://raw.githubusercontent.com/risingwavelabs/risingwave/17af8a747593ebdbfa826691daf75bdab7d14fa0/.github/contributor-license-agreement.txt).

## What's changed and what's your intention?

Related: https://github.com/risingwavelabs/risingwave/pull/24457. Fix #24627

- Fix connector-node integration test failures on Java 21 caused by a shaded gRPC classpath conflict from `iceberg-gcp-bundle`.
- Replace `iceberg-gcp-bundle` with explicit `google-cloud-storage` / `google-cloud-kms` deps (versions aligned to the bundle) to avoid duplicate `io.grpc.*` classes in the release tarball.
- Make the Buildkite upload-failure-logs hook tolerate missing `.risingwave/log` so it doesn't mask the real failure.

## Checklist

- [ ] I have written necessary rustdoc comments.
- [ ]  I have added necessary unit tests and integration tests.
- [ ]  I have added test labels as necessary. 
- [ ]  I have added fuzzing tests or opened an issue to track them. 
- [ ]  My PR contains breaking changes. 
- [ ]  My PR changes performance-critical code, so I will run (micro) benchmarks and present the results. 
- [ ]  I have checked the [Release Timeline](https://github.com/risingwavelabs/rw-commits-history/blob/main/release_timeline.md) and [Currently Supported Versions](https://docs.risingwave.com/changelog/release-support-policy#support-end-dates-for-recent-releases) to determine which release branches I need to cherry-pick this PR into. 

## Documentation

- [ ]  My PR needs documentation updates. 

<details>
<summary><b>Release note</b></summary>

</details>

### CODE REVIEW

**Comment by BugenZhao** [comment]
The GHA failure is another separate issue: #24636

**Comment by chenzl25** [comment]
It seems we miss google-auth-library ?

**Comment by BugenZhao** [comment]
> It seems we miss google-auth-library ?

Seems still there?

image

**Comment by chenzl25** [comment]
cc @tuantran0910 @xxhZs  We found that iceberg-gcp-bundle of previous PR https://github.com/risingwavelabs/risingwave/pull/24457 has caused some issues of integration tests. I think we need to test it whether still work of this PR.

**Comment by chenzl25** [comment]
> Replace iceberg-gcp-bundle with explicit google-cloud-storage / google-cloud-kms deps (versions aligned to the bundle) to avoid duplicate io.grpc.* classes in the release tarball.

Does it mean we only include google-cloud-storage and google-cloud-kms from iceberg-gcp-bundle without google-auth-library? Or where google-auth-library is from?

**Comment by BugenZhao** [comment]
> Or where google-auth-library is from?

It seems to be an indirect dep of `storage` and `kms`. I feel like the main problem is that we don't have any coverage on whether this works.

**Comment by chenzl25** [comment]
> It seems to be an indirect dep of storage and kms. I feel like the main problem is that we don't have any coverage on whether this works.

Indeed. Let @xxhZs  and @tuantran0910  to confirm whether it still works.

**Comment by tuantran0910** [comment]
> > It seems to be an indirect dep of storage and kms. I feel like the main problem is that we don't have any coverage on whether this works.
> 
> Indeed. Let @xxhZs and @tuantran0910 to confirm whether it still works.

Hi @chenzl25, I confirm that it still works!
